apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: angular-docker-kubernetes
spec:
  replicas: 1
  template:
    metadata:
      labels:
        label-key : angular-docker-kubernetes
    spec:
      containers:
        - name: deploment-container-name
          image: nagendra87k/angular-docker-kubernetes
          imagePullPolicy: Always
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service-label-key: service-label-value 
  name: service-name-loadbalancer
spec:
  type: LoadBalancer
  ports:
  - name: service-port-name
    port: 80
    protocol: TCP
  selector:
    deployment-label-key: deployment-label-value
